exit code in prompt

diff --git a/dotfiles/shell/config b/dotfiles/shell/config
--- a/dotfiles/shell/config
+++ b/dotfiles/shell/config
@@ -29,6 +29,8 @@ shopt -s cmdhist
 
 # set up prompt
 function prompt_command() {
+	exitCode=$?
+		
 	# display git branch in prompt
 	if [ "\$(type -t __git_ps1)" ]; then # if we're in a Git repo, show current branch
 		BRANCH="\$(__git_ps1 '[%s] ')"
@@ -37,15 +39,32 @@ function prompt_command() {
 	fi
 
 	local TIME="\A"
-	local USER_HOST="\u@\h"
 	local PATH="\w"
+	local RESET='\[\e[0m\]'
+	local WHITE='\[\e[1;37m\]'
+	local GREEN='\[\e[1;32m\]'
+	local CYAN='\[\e[1;36m\]'
+	local RED='\[\e[1;31m\]'
 
-	# return color to Terminal setting for text color
-	local DEFAULT="\[\e[0;39m\]"
-	export PS1="\\[\\033[01;37m\\]\\A \\[\\033[01;32m\\]\\u@\\h \\[\\033[01;36m\\]\\w\n${DEFAULT}${BRANCH}$ \\[\\033[00m\\]"
+	# red color for  root
+	if [ $UID -eq 0 ]; then
+		USER_HOST="${RED}\u@\h"
+	else
+		USER_HOST="${GREEN}\u@\h"
+	fi
+
+	# red exit code and dollar prompt if non-zero
+	if [ $exitCode -ne 0 ]; then
+		EXIT_CODE="${RED}($exitCode) ${RESET}"
+		DOLLAR="${RED}\$ ${RESET}"
+	else
+		EXIT_CODE=""
+		DOLLAR="\$ "
+	fi
+	export PS1="${RESET}${WHITE}${TIME} ${USER_HOST} ${EXIT_CODE}${CYAN}${PATH}\n${RESET}${BRANCH}${DOLLAR}"
 }
 
 # Whenever displaying the prompt, write the previous line to disk (-a) and read
 # the new line into the history list (-n)
-export PROMPT_COMMAND="history -a; history -n; prompt_command; ${PROMPT_COMMAND}"
+export PROMPT_COMMAND="prompt_command; history -a; history -n; ${PROMPT_COMMAND}"
 
